### ISSUE TITLE
Change 'Contact' link in Nav bar to 'Help'

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#132]
Current Contact page is to be a child of the Help page.

**Comment by TazHinkle** [comment]
Saved as Draft in the Appearance > Menus editor.  I Changed the Nav bar to read Help instead of Contact.  Clicking Help directly leads to the Genealogy Research Page.  Contact is a child link that displays when Help is hovered over in the Nav bar.

**Comment by DeniseColbert** [comment]
I can't find the drafts in the Menus editor @TazHinkle, by lack of familiarity with WP I'm afraid. Could you maybe send a few screen grabs or a short video so I can find it and have a look? If not, you can just share your screen on Thursday :)

**Comment by TazHinkle** [comment]
I did go about it in an odd way.  I've since learned there are multiple
ways to mess with the menu.  I like the visual aspect of this method, but
it is not amazingly easy to get to…  I'll put in some screen caps, but I'll
be ready to share my screen Thursday if need be.
[image: menuDraft1.png]
[image: menuDraft2.png][image: menuDraft3.png]
[image: menuDraft4.png][image: menuDraft5.png]
The interface I used involves clicking on the "Header" option under
"Appearance", clicking the back arrow twice, and then going into "Menu"
then "Header Menu".  There you can see the site as it would look and click
on the links to test where they're pointing.

**Comment by DeniseColbert** [comment]
Ah ok, thanks Taz. The screenshots didn't work but I followed your steps and found the preview. It all looks fine so I published it :)
