### ISSUE TITLE
Look for a free carousel Twitter feed, ideally customisable to branding

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#34]
Or source a separate, better Twitter plugin

**Comment by DeniseColbert** [comment]
@carcarvroom The Our Story page (About Us should be changed to Our Story in Nav bar) had a Twitter widget that we really liked. It isn't there now- are you able to track it down?

**Comment by carcarvroom** [comment]
I think that widget was specific to Beaver Builder, but let me try some other options and see if I can get some type of scrolling function. If not, I think that function can be added from the PHP end.

- [ x ] Changed About Us to Our Story in nav bar
- [ ] Add scrolling Twitter feed functionality

**Comment by DeniseColbert** [comment]
Great, thanks!

**Comment by DeniseColbert** [comment]
Found this plugin: https://en-gb.wordpress.org/plugins/custom-twitter-feeds/

High number of users, recently updated.

**Comment by DeniseColbert** [comment]
@hotbeverage2017 could you take a look at this plugin for Twitter please?

**Comment by ghost** [comment]
@DeniseColbert since this Twitter plugin mentions something about being able to "Load More" I think that might be what you want. In any case, it won't hurt to plug it in and try it out.

You have three other plugins that need an update. I can update those plus add this plug to the site and try it out. John would be working earlier than I come in, Taz later than I possibly stay. I usually like to do this when no-one is likely to be using the site. Elementor is the big one, really, because I especially don't want to update that when people might be using it.

Any suggestions on day/time? It's not going to take me long to do all this. Definitely not more than 15 minutes, but probably not nearly that long.

**Comment by ghost** [comment]
@DeniseColbert I had added the Twitter feed plugin and have these questions:
1. In the Page "Our Story" is the Twitter feed supposed to go into the right hand side panel?
2. To configure the Twitter feed, there needs to be a feed to point to. Or, there is a way to get an access token and secret. I'm not sure what to use for these. I don't have a Twitter account, so it's not something I can play around with without these.

**Comment by DeniseColbert** [comment]
If we can't find a free carousel plugin then use this one ^

**Comment by DeniseColbert** [comment]
We have the ability to show multiple tweets so closing
